### PR TITLE
recipes: Add missing Upstream Status tag

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by nsdrude** [comment]
@kraj Can you please update the patches explaining why?

**Comment by kraj** [comment]
latest master branch of poky has started to emit build QA errors if patches are missing Upstream-Status: and Signed-off-by tags. this patch makes sure that we can build with master branch.

**Comment by nsdrude** [comment]
Please resubmit this to  [langdale-var01](https://github.com/varigit/meta-variscite-bsp/tree/langdale-var01)

**Comment by kraj** [comment]
> Please resubmit this to [langdale-var01](https://github.com/varigit/meta-variscite-bsp/tree/langdale-var01)

this was against langdale-var01 branch. Why was it closed without merge ?

**Comment by kraj** [comment]
closing in favour of https://github.com/varigit/meta-variscite-bsp/pull/27

**Pull request closed without merging**
