### PR TITLE
IMX6: add kirkstone support

### PR DESCRIPTION
**Pull request by moto-timo**
Add linux-variscite 5.10 support for mx6 platforms.

https://github.com/varigit/meta-variscite-bsp/issues/10

Tested on DART-6UL

### CODE REVIEW

**Comment by moto-timo** [comment]
This blocks updating `meta-mender-variscite` to `kirkstone`.  https://github.com/moto-timo/meta-mender-community/tree/variscite-bsp-kirkstone

**Comment by moto-timo** [comment]
Crickets. This works. We need it. Please try.

**Comment by m-tmatma** [comment]
@moto-timo 
`recipes-kernel/linux/linux-variscite_5.15.bb` already exists on `kirkstone` branch.
Why do you try to add `recipes-kernel/linux/linux-variscite_5.10.bb`?
(I mean you can add IMX6 support to `recipes-kernel/linux/linux-variscite_5.15.bb`)

**Comment by nsdrude** [comment]
Following Variscite's Yocto Kirkstone release for imx6/6ul/7, I am closing this PR.

**Comment by moto-timo** [comment]
@m-tmatma 
> @moto-timo `recipes-kernel/linux/linux-variscite_5.15.bb` already exists on `kirkstone` branch. Why do you try to add `recipes-kernel/linux/linux-variscite_5.10.bb`? (I mean you can add IMX6 support to `recipes-kernel/linux/linux-variscite_5.15.bb`)

At the time I filed the PR, there was no support in the 5.15 branch for the imx6ul-var-dart. You all added that later in [May](https://github.com/varigit/linux-imx/commit/02be52bb02f6454ba80127796c546f2c81795687).
Thank you for continuing to support the platform, as it is still in service in the field.

**Pull request closed without merging**
